# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36b67d6e4b79f75c7f73aa8e942dca7e997b3fa3a24b8ac7a9c910f15519ec9e818d3b75cd407360f91497388f5367460b000fd5b36627dbd32d85cdcf0e87aa

test:
  secret_key_base: 7894ba2838559b1f7586582cb1d04646b0b60c99add93fdcc91837dc8743a46d27bb732b9c862f0ff79cbbc905e5283ca44ab6d8f1fb9dcf3bacceba7b100760

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
